myrobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

    # Position Controllers ---------------------------------------
  wheel3_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel3_joint
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  wheel4_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel4_joint
    pid: { p: 100.0, i: 0.01, d: 10.0 }

    # Effort Controllers  big wheel_joints---------------------------------------
  wheel34_Effort_controller:
    type: effort_controllers/JointGroupEffortController
    joints:
      - wheel3_joint
      - wheel4_joint
    # Effort Controllers   leg12_joints leg upper---------------------------------------

  ##### position controller
  leg1423_Effort_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - leg1_joint
      - leg4_joint
      - leg2_joint
      - leg3_joint
    leg1_joint:
      pid: { p: 100.0, i: 0.01, d: 0.50 }
    leg4_joint:
      pid: { p: 100.0, i: 0.01, d: 0.50 }
    leg2_joint:
      pid: { p: 100.0, i: 0.01, d: 0.50 }
    leg3_joint:
      pid: { p: 100.0, i: 0.01, d: 0.50 }


##### Effort controller
  # leg1423_Effort_controller:
  #   type: effort_controllers/JointGroupEffortController
  #   joints:
  #     - leg1_joint
  #     - leg4_joint
  #     - leg2_joint
  #     - leg3_joint


  # leg1_joint_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: leg1_joint
  # leg2_joint_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: leg2_joint
  # leg3_joint_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: leg3_joint
  # leg4_joint_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: leg4_joint

  # Effort Controllers  big wheel_joints---------------------------------------
  wheel12_Effort_controller:
    type: effort_controllers/JointGroupEffortController
    joints:
      - wheel1_joint
      - wheel2_joint

  left_wheel_controller:
    type: effort_controllers/JointEffortController
    joint: wheel1_joint

  right_wheel_controller:
    type: effort_controllers/JointEffortController
    joint: wheel2_joint
